main:
  plugins: 
  - Scan: Scan::Default # adds 'File::Dedupe::Plugin::' automatically
default: 
  description: default profile to check if deduper works
  action: delete
  input:
   - dir: '/home/maurice/projects/dedupe' #recursive
   - dir: '/home/maurice/projects/dedupe' #recursive
   - single_dir: '/home/maurice/projects/dedupe' #only one dir
   - file: '/home/maurice/projects/dedupe/README.pod'
#  strategy: file #optional
  selectmajor: lastModified
#  logger: debug #todo don't know yet what config will do
maurice:
  action: delete
  input:
   - dir: '/home/maurice/projects/dedupe'
